export default {
    "MARK_NOTIFICATIONS_BY_ID":"MARK_NOTIFICATIONS_BY_ID",
    "MARK_NOTIFICATIONS":"MARK_NOTIFICATIONS",
    "START_NOTIFICATIONS_POST":"START_NOTIFICATIONS_POST",
    "END_NOTIFICATIONS_POST":"END_NOTIFICATIONS_POST",
    "RECEIVE_NOTIFICATIONS":"RECEIVE_NOTIFICATIONS",
    "START_LOGIN":"START_LOGIN",
    "LOGIN_SUCCESS":"LOGIN_SUCCESS",
    "LOGIN_FAILED":"LOGIN_FAILED"
}